from __future__ import annotations

import json
import os
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / "templates/project/template/.github/workflows/copier-update.yml.jinja"


def production_script() -> str:
    content = WORKFLOW.read_text(encoding="utf-8")
    run_block = content.split("        run: |\n", 1)[1]
    script = textwrap.dedent(run_block)
    return script.replace("{% raw %}", "").replace("{% endraw %}", "")


def run_git(*args: str, cwd: Path) -> str:
    result = subprocess.run(
        ["git", *args], cwd=cwd, check=True, text=True, capture_output=True
    )
    return result.stdout.strip()


class CopierUpdateWorkflowTests(unittest.TestCase):
    def setUp(self) -> None:
        self.script = production_script()

    def make_checkout(self, temporary: Path) -> tuple[Path, Path]:
        bare = temporary / "remote.git"
        checkout = temporary / "checkout"
        run_git("init", "--bare", str(bare), cwd=temporary)
        run_git("clone", str(bare), str(checkout), cwd=temporary)
        run_git("config", "user.name", "fixture", cwd=checkout)
        run_git("config", "user.email", "fixture@example.com", cwd=checkout)
        (checkout / "README.md").write_text("fixture\n", encoding="utf-8")
        (checkout / ".copier-answers.yml").write_text(
            "components:\n"
            "  - type: python\n"
            "    path: .\n"
            "    id: app-python\n"
            "    name: Application Python\n",
            encoding="utf-8",
        )
        run_git("add", "README.md", ".copier-answers.yml", cwd=checkout)
        run_git("commit", "-m", "initial", cwd=checkout)
        run_git("push", "origin", "HEAD:refs/heads/main", cwd=checkout)
        return checkout, bare

    def fake_tools(self, temporary: Path) -> Path:
        bin_dir = temporary / "bin"
        bin_dir.mkdir()
        (bin_dir / "gh").write_text(
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "if [[ \" $* \" == *\" --jq .tagName \"* ]]; then printf '%s\\n' \"${LATEST_REF:-v2.21.5}\"; else cat \"$GH_RELEASE_JSON\"; fi\n",
            encoding="utf-8",
        )
        (bin_dir / "copier").write_text(
            "#!/usr/bin/env bash\n"
            "set -euo pipefail\n"
            "printf 'copier-called\\n' >> \"$COPIER_LOG\"\n"
            "printf 'generated by copier\\n' > .copier-created\n",
            encoding="utf-8",
        )
        for tool in (bin_dir / "gh", bin_dir / "copier"):
            tool.chmod(0o755)
        return bin_dir

    def execute(
        self, checkout: Path, temporary: Path, release: dict, template_ref: str = "v2.21.5"
    ) -> subprocess.CompletedProcess[str]:
        release_file = temporary / "release.json"
        release_file.write_text(json.dumps(release), encoding="utf-8")
        copier_log = temporary / "copier.log"
        env = {
            **os.environ,
            "PATH": f"{self.fake_tools(temporary)}:{os.environ['PATH']}",
            "TEMPLATE_REF": template_ref,
            "GH_RELEASE_JSON": str(release_file),
            "COPIER_LOG": str(copier_log),
            "GITHUB_STEP_SUMMARY": str(temporary / "summary.md"),
            "GITHUB_SERVER_URL": "https://github.com",
            "GITHUB_REPOSITORY": "fixture/project",
            "DEFAULT_BRANCH": "main",
            "BRANCH": "automation/copier-template-update",
        }
        return subprocess.run(
            ["bash", "-c", self.script], cwd=checkout, env=env, text=True, capture_output=True
        )

    def test_published_stable_tag_allows_copier_and_pushes_add_only_file(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            temporary = Path(raw)
            checkout, bare = self.make_checkout(temporary)
            result = self.execute(
                checkout,
                temporary,
                {"tagName": "v2.21.5", "publishedAt": "2026-09-01T00:00:00Z", "isDraft": False, "isPrerelease": False},
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual((temporary / "copier.log").read_text(encoding="utf-8"), "copier-called\n")
            remote_tree = run_git("--git-dir", str(bare), "ls-tree", "-r", "--name-only", "automation/copier-template-update", cwd=temporary)
            self.assertIn(".copier-created", remote_tree.splitlines())
            remote_commit = run_git("--git-dir", str(bare), "log", "-1", "--format=%s", "automation/copier-template-update", cwd=temporary)
            self.assertEqual(remote_commit, "chore(template): update shared project template")

    def test_yaml_dependency_is_in_test_setup_not_generated_update_workflow(self) -> None:
        self.assertNotIn("pip install --disable-pip-version-check --quiet PyYAML==6.0.3", self.script)
        validation_workflow = (ROOT / ".github/workflows/validate-toolkit.yml").read_text(encoding="utf-8")
        self.assertIn("python -m pip install PyYAML==6.0.3 copier==9.18.2", validation_workflow)

    def test_unreleased_or_mismatched_release_ref_stops_before_copier(self) -> None:
        cases = [
            ("v2.21.5", {"tagName": "v2.21.4", "publishedAt": "2026-09-01T00:00:00Z", "isDraft": False, "isPrerelease": False}),
            ("v2.21.5", {"tagName": "v2.21.5", "publishedAt": None, "isDraft": False, "isPrerelease": False}),
            ("v2.21.5", {"tagName": "v2.21.5", "publishedAt": "2026-09-01T00:00:00Z", "isDraft": True, "isPrerelease": False}),
            ("v2.21.5", {"tagName": "v2.21.5", "publishedAt": "2026-09-01T00:00:00Z", "isDraft": False, "isPrerelease": True}),
            ("main", {"tagName": "main", "publishedAt": "2026-09-01T00:00:00Z", "isDraft": False, "isPrerelease": False}),
            ("b13b2d1604dbde783d0ee23ac01f41c1853fd665", {"tagName": "b13b2d1604dbde783d0ee23ac01f41c1853fd665", "publishedAt": "2026-09-01T00:00:00Z", "isDraft": False, "isPrerelease": False}),
        ]
        for template_ref, release in cases:
            with self.subTest(template_ref=template_ref, release=release), tempfile.TemporaryDirectory() as raw:
                temporary = Path(raw)
                checkout, _ = self.make_checkout(temporary)
                result = self.execute(checkout, temporary, release, template_ref)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn("Refused template ref", result.stderr)
                self.assertFalse((temporary / "copier.log").exists())


if __name__ == "__main__":
    unittest.main()
