name: Java CI
on: [pull_request]
permissions:
  contents: read
jobs:
  java:
    uses: quokkify/project-toolkit/.github/workflows/java-ci.yml@v2.3.0
    with:
      java-version: "21"
      build-tool: auto
