name: Product release
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    uses: ylazakovich/project-toolkit/.github/workflows/release-please.yml@v1.0.0
    with:
      mode: single
      release-type: simple
